name: Deploy to Production

on:
  push:
    branches: ['main']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 1. Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chess-backend:latest
          # Optimization: Cache layers to speed up future builds
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chess-backend:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chess-backend:cache,mode=max

      # 2. Build & Push WebSocket
      - name: Build and Push WS
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/ws/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chess-ws:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chess-ws:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chess-ws:cache,mode=max

      # 3. Build & Push Frontend (With Args)
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/chess-frontend:latest
          # CRITICAL: Pass the production URLs here
          build-args: |
            VITE_APP_BACKEND_URL=/
            VITE_APP_WS_URL=wss://chessverse.lumenvault.live/ws
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chess-frontend:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/chess-frontend:cache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d "ChessVerse" ]; then
              git clone https://github.com/surajbkale/ChessVerse.git
            fi
            cd ChessVerse
            git pull origin main

            sudo docker compose -f docker-compose.prod.yml pull

            sudo docker compose -f docker-compose.prod.yml up -d --remove-orphans

            sudo docker image prune -f
